### ISSUE TITLE
HTTP response body: {"error": "User is not authenticated"}

### ISSUE THREAD

**Issue by wangzhe112-lab** [Rachum-thu/DebugBench#1]
![image](https://github.com/thunlp/DebugBench/assets/56470984/aa82aab6-22f7-470f-b745-cfdb4440f2f2)

**Comment by runchu-tian** [comment]
This happens when the LeetCode server finds your cookie invalid.

Here are some common reasons:

- You manually log out (rather than close the page) of or switch the account after obtaining the cookie.
- Your account has not been verified by e-mail.
- your account is not for `leetcode.com` but for parallel websites like `leetcode.cn`

**Comment by runchu-tian** [comment]
This is how I obtained mine.

#### 1. Go to `leetcode.com`
> Notice that the leetcode OJ environment is not compatible with `leetcode.cn`

#### 2. Log in to your account
> Just to let you know, you must have your account **verified** by e-mail before you use it.

#### 3. Activate the developer view of your browser
> For example, if you are using Chrome, this will be `View` > `Developer` > `Developer Tools`.

#### 4. Obtain the cookie
> Go to `Storage` > `Cookies` > `leetcode.com`.  

> Copy the `LEETCODE_SESSION` entry. It should look like a long long string as `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiMTEyNzM3OTYiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZG......`

#### 5. Do not manually log out or switch accounts.

> It is OK if you close the web page. But manually logging out or switching accounts makes your cookie **invalid**.

> If you really want to switch accounts, you may use the anonymous mode of your browser to get the cookie and close the page after that.

**Comment by runchu-tian** [comment]
I closed the issue for now since I think my reply should resolve your problem. Welcome to re-open it if you have more issues.

**Comment by shuaiwang2022** [comment]
![Uploading image.png…]()
However, it suffers from the above problems

**Comment by YaseenMajdoob** [comment]
I had the same error today, I've tried all the steps and still can't fix it

**Comment by runchu-tian** [comment]
> I had the same error today, I've tried all the steps and still can't fix it

I have tested the code today and it works well for me when the cookie is correct.

So from my perspectives, it is likely that you are getting an improper cookie.

Please leave your e-mail so that I can send you the cookie I use. You can try that out. If this cookie also works well for you, the code of this repository should be flawless. 

<img width="1113" alt="Screenshot 2024-05-17 at 11 34 40" src="https://github.com/thunlp/DebugBench/assets/102339729/68a66a29-20c1-4e4a-a45d-81a265614fa4">

**Comment by runchu-tian** [comment]
> I had the same error today, I've tried all the steps and still can't fix it

If this problem continually bothers you, we can have a brief zoom meeting to solve it if you like :)

**Comment by xuhaolei** [comment]
> > I had the same error today, I've tried all the steps and still can't fix it
> 
> If this problem continually bothers you, we can have a brief zoom meeting to solve it if you like :)

I had the similar error, I follow your step and I think my cookie is right. Do you have time to test the code again? Maybe leetcode has changed something.
![image](https://github.com/user-attachments/assets/b45302a4-7666-4fad-9681-cb06c796ee21)

**Comment by runchu-tian** [comment]
@xuhaolei Hi, I have udpated leetcode_oj module. Now we should pass BOTH `leetcode_session` and `csrf_token` to the `LeetCodeTester` like this

```python
leetcode_session = os.environ['LEETCODE_SESSION']
csrf_token = os.environ['CSRF_TOKEN']

class LeetCodeTester(object):

    def __init__(self, leetcode_session: str=None, csrf_token: str=None, cooldown: int=10):

        self.env = LeetCodeEnv(cooldown=cooldown, leetcode_session=leetcode_session, csrf_token=csrf_token)
        self.lang_dict = {
            "python": ProgrammingLanguage.PYTHON3,
            "python3": ProgrammingLanguage.PYTHON3,
            "java": ProgrammingLanguage.JAVA,
            "c": ProgrammingLanguage.C,
            "cpp": ProgrammingLanguage.CPP,
        }

    def test(self, code: str, task_id: str, language: str) -> tuple[bool, dict]:

        lang = self.lang_dict.get(language)
        sub = LeetCodeSubmission(code=code, lang=lang, question_slug=task_id)
        status, reward, done, submission_result = self.env.step(sub)
        return reward, submission_result


if __name__ == '__main__':

    tester = LeetCodeTester(leetcode_session=leetcode_session, csrf_token=csrf_token, cooldown=10)
    task_id = TEST_CASE['task_id']
    code0 = TEST_CASE['original_code']
    code1 = TEST_CASE['problematic_code']
    codes = [code0, code1]

    for code in codes:
        print(tester.test(code, task_id, "python"))
```

And this should work. Please inform me if you need more help.
<img width="936" alt="Screenshot 2024-07-13 at 10 38 27" src="https://github.com/user-attachments/assets/a2a7f451-b6f0-4276-a3a6-e2b66705b06d">

**Comment by runchu-tian** [comment]
@xuhaolei Please e-mail me at runchutian@gmail.com if you need further assistance like zoom meeting or something.

**Comment by TYrant-TY** [comment]
@Rachum-thu 
I followed your steps, but I encountered a similar error. Do you have time to test the code again?
![image](https://github.com/user-attachments/assets/dd7fac7b-c509-48ea-bf1b-c722b288db79)
I

**Comment by runchu-tian** [comment]
It has been observed by a kind researcher from CMU that the LeetCode 403 error (IP blocking) can also occur due to repeatedly submitting identical test cases (in `evaluation/leetcode_oj/leetcode_tester_pool.py`). Changing Instances of the submitted code or test cases may resolve this issue.
