### ISSUE TITLE
leetcode.rest.ApiException: (403) Reason: Forbidden

### ISSUE THREAD

**Issue by TYrant-TY** [Rachum-thu/DebugBench#4]
![image](https://github.com/user-attachments/assets/9a81334f-f8fd-4e1f-bb4a-778d64b27046)
I've tried many methods but still haven't been able to solve it.

**Comment by Rachum-thu** [comment]
Sorry for the inconvenience caused. I also encounter this issue from time to time. The reason of this Exception is your requests are recognized as malicious traffic from Cloudflare, the website protection provider for LeetCode. Such a mechanism will be **periodically** activated for the LeetCode API. 

But this situation typically will not last for a long time. When I tested the OJ after getting you issue, it was already quite available. Please try again with your leetcode_session and csrf_token. 

If you need further help, feel free to e-mail me.

**Comment by runchu-tian** [comment]
Sorry for the inconvenience caused. I also encounter this issue from time to time. The reason of this Exception is your requests are recognized as malicious traffic from Cloudflare, the website protection provider for LeetCode. Such a mechanism will be **periodically** activated for the LeetCode API.

But this situation typically will not last for a long time. When I tested the OJ after getting you issue, it was already quite available. Please try again with your leetcode_session and csrf_token.

If you need further help, feel free to e-mail me.

**Comment by TYrant-TY** [comment]
@Rachum-thu 
Thank you for your reply, but it still doesn't work for me. I wonder if it's a problem with my account, as this account is newly created and I'm not sure if there are any additional settings required. I tried to access https://leetcode.com/api/problems/two-sum/ and https://leetcode.com/problems/two-sum/submit/ separately, and found that one was successfully accessed but the information was empty, while the other failed.

![Uploading image.png…]()

![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by TYrant-TY** [comment]
@Rachum-thu Thank you for your reply, but it still doesn't work for me. I wonder if it's a problem with my account, as this account is newly created and I'm not sure if there are any additional settings required. I tried to access https://leetcode.com/api/problems/two-sum/ and https://leetcode.com/problems/two-sum/submit/ separately, and found that one was successfully accessed, while the other failed.

![Uploading image.png…]()
![Uploading image.png…]()

![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
However, I was using Edge before, and when I used the cookie from Edge to test this https://leetcode.com/api/problems/two-sum/, there was no username. When I used the cookie from Google to test, there was a username, but ultimately running leetcode_tester.py still failed.
